# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ced58b9e8fcfc2991095a9efe2e68753aa06d7bb662213cd542a735c2c368730b41e733ada23ea7a1d01d32efddbfc008b02c30da2df6425632dbbafa5262697

test:
  secret_key_base: 03d0b090c559c071708dfb4bce4849bd408b3866251a11741084badd3600405176a70ff7a02021be6df6a326e238ca5fb738c5ecd5644751df74c7c13bd32ec5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
